ALTER TABLE categories
    ADD COLUMN IF NOT EXISTS display_name VARCHAR(255);

--LEVEL 0 CATEGORIES
INSERT INTO categories (sid, name, display_name, parent_id, user_sid, created_at, updated_at)
VALUES (gen_random_uuid(), 'HOUSING', 'Housing', null, null, now(), now()),
       (gen_random_uuid(), 'TRANSPORTATION', 'Transportation', null, null, now(), now()),
       (gen_random_uuid(), 'LEISURE', 'Leisure', null, null, now(), now()),
       (gen_random_uuid(), 'INVESTMENTS', 'Investments', null, null, now(), now()),
       (gen_random_uuid(), 'SYSTEM', null, null, null, now(), now()),
       (gen_random_uuid(), 'PERSONAL_CARE', 'Personal Care', null, null, now(), now()),
       (gen_random_uuid(), 'PETS', 'Pets', null, null, now(), now()),
       (gen_random_uuid(), 'GIFTS', 'Gifts', null, null, now(), now()),
       (gen_random_uuid(), 'CLOTHING', 'Clothing', null, null, now(), now()),
       (gen_random_uuid(), 'GADGETS', 'Gadgets', null, null, now(), now()),
       (gen_random_uuid(), 'HEALTH', 'Health', null, null, now(), now()),
       (gen_random_uuid(), 'INCOME', 'Income', null, null, now(), now()),
       (gen_random_uuid(), 'TAXES', 'Taxes', null, null, now(), now());

--LEVEL 1 CATEGORIES
INSERT INTO categories (sid, name, display_name, parent_id, user_sid, created_at, updated_at)
VALUES (gen_random_uuid(), 'INITIAL_BALANCE', null,
        (SELECT id FROM categories WHERE name = 'SYSTEM'),
        null, now(), now()),
       (gen_random_uuid(), 'DIESEL', 'Diesel',
        (SELECT id FROM categories WHERE name = 'TRANSPORTATION'),
        null, now(), now()),
       (gen_random_uuid(), 'GASOLINE', 'Gasoline',
        (SELECT id FROM categories WHERE name = 'TRANSPORTATION'),
        null, now(), now()),
       (gen_random_uuid(), 'TOLLS', 'Tolls',
        (SELECT id FROM categories WHERE name = 'TRANSPORTATION'),
        null, now(), now()),
       (gen_random_uuid(), 'INSURANCE', 'Insurance',
        (SELECT id FROM categories WHERE name = 'TRANSPORTATION'),
        null, now(), now()),
       (gen_random_uuid(), 'MORTGAGE_PAYMENT', 'Mortgage Payment',
        (SELECT id FROM categories WHERE name = 'HOUSING'),
        null, now(), now()),
       (gen_random_uuid(), 'CONDOMINIUM', 'Condominium',
        (SELECT id FROM categories WHERE name = 'HOUSING'),
        null, now(), now()),
       (gen_random_uuid(), 'INSURANCE', 'Insurance',
        (SELECT id FROM categories WHERE name = 'HOUSING'),
        null, now(), now()),
       (gen_random_uuid(), 'UTILITIES', 'Utilities',
        (SELECT id FROM categories WHERE name = 'HOUSING'),
        null, now(), now()),
       (gen_random_uuid(), 'GROCERIES', 'Groceries',
        (SELECT id FROM categories WHERE name = 'HOUSING'),
        null, now(), now()),
       (gen_random_uuid(), 'BARBER', 'Barber',
        (SELECT id FROM categories WHERE name = 'PERSONAL_CARE'),
        null, now(), now()),
       (gen_random_uuid(), 'HAIRDRESSER', 'Hairdresser',
        (SELECT id FROM categories WHERE name = 'PERSONAL_CARE'),
        null, now(), now()),
       (gen_random_uuid(), 'BEAUTICIAN', 'Beautician',
        (SELECT id FROM categories WHERE name = 'PERSONAL_CARE'),
        null, now(), now()),
       (gen_random_uuid(), 'GYM', 'Gym',
        (SELECT id FROM categories WHERE name = 'PERSONAL_CARE'),
        null, now(), now()),
       (gen_random_uuid(), 'VETERINARIAN', 'Veterinarian',
        (SELECT id FROM categories WHERE name = 'PETS'),
        null, now(), now()),
       (gen_random_uuid(), 'PET_FOOD', 'Pet Food',
        (SELECT id FROM categories WHERE name = 'PETS'),
        null, now(), now()),
       (gen_random_uuid(), 'APPOINTMENTS', 'Appointments',
        (SELECT id FROM categories WHERE name = 'HEALTH'),
        null, now(), now()),
       (gen_random_uuid(), 'PHARMACY', 'Pharmacy',
        (SELECT id FROM categories WHERE name = 'HEALTH'),
        null, now(), now()),
       (gen_random_uuid(), 'SALARY', 'Salary',
        (SELECT id FROM categories WHERE name = 'INCOME'),
        null, now(), now()),
       (gen_random_uuid(), 'FOOD_ALLOWANCE', 'Food Allowance',
        (SELECT id FROM categories WHERE name = 'INCOME'),
        null, now(), now()),
       (gen_random_uuid(), 'RESTAURANTS', 'Restaurants',
        (SELECT id FROM categories WHERE name = 'LEISURE'),
        null, now(), now()),
       (gen_random_uuid(), 'BARS', 'Bars',
        (SELECT id FROM categories WHERE name = 'LEISURE'),
        null, now(), now()),
       (gen_random_uuid(), 'EXPERIENCES', 'Experiences',
        (SELECT id FROM categories WHERE name = 'LEISURE'),
        null, now(), now());

--LEVEL 2 CATEGORIES
INSERT INTO categories (sid, name, display_name, parent_id, user_sid, created_at, updated_at)
VALUES (gen_random_uuid(), 'ELECTRICITY', 'Electricity',
        (SELECT id FROM categories WHERE name = 'UTILITIES'),
        null, now(), now()),
       (gen_random_uuid(), 'GAS', 'Gas',
        (SELECT id FROM categories WHERE name = 'UTILITIES'),
        null, now(), now()),
       (gen_random_uuid(), 'WATER', 'Water',
        (SELECT id FROM categories WHERE name = 'UTILITIES'),
        null, now(), now()),
       (gen_random_uuid(), 'COMMUNICATIONS', 'Communications',
        (SELECT id FROM categories WHERE name = 'UTILITIES'),
        null, now(), now()),
       (gen_random_uuid(), 'LIFE_INSURANCE', 'Life Insurance',
        (SELECT id FROM categories WHERE name = 'INSURANCE' and parent_id = (SELECT id FROM categories WHERE name = 'HOUSING')),
        null, now(), now()),
       (gen_random_uuid(), 'HOUSE_INSURANCE', 'House Insurance',
        (SELECT id FROM categories WHERE name = 'INSURANCE' and parent_id = (SELECT id FROM categories WHERE name = 'HOUSING')),
        null, now(), now());