spring:
  application:
    name: Graveto
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${GRAVETO_POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:graveto_db}
    username: ${POSTGRES_APP_USER:graveto_app_user}
    password: ${POSTGRES_APP_PASSWORD:graveto_app_password}
  flyway:
    url: jdbc:postgresql://${GRAVETO_POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:graveto_db}
    user: ${POSTGRES_MIGRATOR_USER:graveto_migrator_user}
    password: ${POSTGRES_MIGRATOR_PASSWORD:graveto_migrator_password}
    locations:
      - classpath:db/migration/common
      - classpath:db/migration/moneytracker
      - classpath:db/migration/identity
      - classpath:db/migration/portfolio

server:
  servlet:
    context-path: /api
logging:
  structured:
    format:
      console: ecs
    json:
      stacktrace:
        root: first
        max-length: 1024
  level:
    org.springframework.web: INFO

jwt:
  signing-secret: jwt_graveto_secret
  expiration-ms: 3600000
  issuer: >
    graveto-api

http:
  client:
    connect-timeout: 10000
    read-timeout: 10000
    max-requests: 5
    request-cooldown-ms: 60000
    yahoo:
      api-key: ${YFINANCE_API_KEY:yfinance_api_key}
      base-url: https://yfapi.net/
      search:
        path: v6/finance/autocomplete
      quote:
        path: v6/finance/quote
        batch-limit: 10

scheduled:
  cron:
    asset-price: 0 30 10,17 * * *
    recurring-transaction: 0 0 10 * * *
