#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_MIGRATOR_USER WITH PASSWORD '$POSTGRES_MIGRATOR_PASSWORD';
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_MIGRATOR_USER;
    GRANT CREATE ON SCHEMA public TO $POSTGRES_MIGRATOR_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $POSTGRES_MIGRATOR_USER;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $POSTGRES_MIGRATOR_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $POSTGRES_MIGRATOR_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $POSTGRES_MIGRATOR_USER;
    CREATE USER $POSTGRES_APP_USER WITH PASSWORD '$POSTGRES_APP_PASSWORD';
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_APP_USER;
    GRANT USAGE ON SCHEMA public TO $POSTGRES_APP_USER;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $POSTGRES_APP_USER;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO $POSTGRES_APP_USER;
    ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_MIGRATOR_USER IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $POSTGRES_APP_USER;
    ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_MIGRATOR_USER IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO $POSTGRES_APP_USER;
EOSQL