ALTER TABLE assets
    ADD COLUMN IF NOT EXISTS stock_exchange_id BIGINT NOT NULL;

CREATE SEQUENCE IF NOT EXISTS stock_exchanges_id_seq
    INCREMENT BY 1
    NO MAXVALUE
    NO MINVALUE
    CACHE 1;

CREATE TABLE IF NOT EXISTS stock_exchanges
(
    id         BIGINT DEFAULT NEXTVAL('stock_exchanges_id_seq') PRIMARY KEY,
    sid        UUID UNIQUE  NOT NULL,
    country_id BIGINT       NOT NULL,
    market     VARCHAR(255) NOT NULL,
    suffix     VARCHAR(10),
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,

    CONSTRAINT stock_exchange_country_fk FOREIGN KEY (country_id) REFERENCES countries (id)
);

INSERT INTO stock_exchanges (sid, country_id, market, suffix, created_at, updated_at)
VALUES (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Argentina'), 'Buenos Aires Stock Exchange (BYMA)',
        '.BA', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Australia'), 'Australian Stock Exchange', '.AX',
        NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Austria'), 'Vienna Stock Exchange', '.VI', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Belgium'), 'Euronext Brussels', '.BR', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Brazil'), 'Sao Paolo Stock Exchange (BOVESPA)',
        '.SA', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Canada'),
        'Canadian Securities ExchangeToronto Stock Exchange', '.CN', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Canada'), 'NEO Exchange', '.NE', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Canada'), 'Toronto Stock Exchange', '.TO', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Canada'), 'TSX Venture Exchange (TSXV)', '.V', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Chile'), 'Santiago Stock Exchange', '.SN', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'China'), 'Shanghai Stock Exchange', '.SS', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'China'), 'Shenzhen Stock Exchange', '.SZ', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Czechia'), 'Prague Stock Exchange Index',
        '.PR', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Denmark'), 'Nasdaq OMX Copenhagen', '.CO', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Egypt'), 'Egyptian Exchange Index (EGID)', '.CA',
        NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Estonia'), 'Nasdaq OMX Tallinn', '.TL', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Finland'), 'Nasdaq OMX Helsinki', '.HE', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'France'), 'Euronext', '.NX', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'France'), 'Euronext Paris', '.PA', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Germany'), 'Berlin Stock Exchange', '.BE', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Germany'), 'Bremen Stock Exchange', '.BM', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Germany'), 'Dusseldorf Stock Exchange', '.DU', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Germany'), 'Frankfurt Stock Exchange', '.F', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Germany'), 'Hamburg Stock Exchange', '.HM', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Germany'), 'Hanover Stock Exchange', '.HA', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Germany'), 'Munich Stock Exchange', '.MU', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Germany'), 'Stuttgart Stock Exchange', '.SG', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Germany'), 'Deutsche Boerse XETRA', '.DE', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Greece'), 'Athens Stock Exchange (ATHEX)', '.AT',
        NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Hong Kong'), 'Hong Kong Stock Exchange (HKEX)',
        '.HK', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Hungary'), 'Budapest Stock Exchange', '.BD', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Iceland'), 'Nasdaq OMX Iceland', '.IC', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'India'), 'Bombay Stock Exchange', '.BO', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'India'), 'National Stock Exchange of India', '.NS',
        NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Indonesia'), 'Indonesia Stock Exchange (IDX)', '.JK',
        NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Ireland'), 'Euronext Dublin', '.IR', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Israel'), 'Tel Aviv Stock Exchange', '.TA', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Italy'), 'EuroTLX', '.TI', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Italy'), 'Italian Stock Exchange, former Milano',
        '.MI', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Japan'), 'Nikkei Indices', NULL, NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Japan'), 'Tokyo Stock Exchange', '.T', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Latvia'), 'Nasdaq OMX Riga', '.RG', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Lithuania'), 'Nasdaq OMX Vilnius', '.VS', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Malaysia'), 'Malaysian Stock Exchange', '.KL', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Mexico'), 'Mexico Stock Exchange (BMV)', '.MX',
        NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Netherlands (the)'), 'Euronext Amsterdam', '.AS', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'New Zealand'), 'New Zealand Stock Exchange (NZX)',
        '.NZ', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Norway'), 'Oslo Stock Exchange', '.OL', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Portugal'), 'Euronext Lisbon', '.LS', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Qatar'), 'Qatar Stock Exchange', '.QA', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Russian Federation (the)'), 'Moscow Exchange (MOEX)', '.ME', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Singapore'), 'Singapore Stock Exchange', '.SI',
        NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Korea (the Republic of)'), 'Johannesburg Stock Exchange', '.Jo',
        NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Korea (the Republic of)'), 'Korea Stock Exchange', '.KS', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Korea (the Republic of)'), 'KOSDAQ', '.KQ', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Spain'), 'Madrid SE C.A.T.S.', '.MC', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Saudi Arabia'), 'Saudi Stock Exchange (Tadawul)',
        '.SAU', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Sweden'), 'Nasdaq OMX Stockholm', '.ST', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Switzerland'), 'Swiss Exchange (SIX)', '.SW', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Taiwan (Province of China)'), 'Taiwan OTC Exchange', '.TWO', NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Taiwan (Province of China)'), 'Taiwan Stock Exchange (TWSE)', '.TW',
        NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Thailand'), 'Stock Exchange of Thailand (SET)',
        '.BK', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Turkey'), 'Borsa İstanbul', '.IS', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'United Kingdom of Great Britain and Northern Ireland (the)'), 'FTSE Indices', NULL, NOW(),
        NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'United Kingdom of Great Britain and Northern Ireland (the)'), 'London Stock Exchange', '.L',
        NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'United Kingdom of Great Britain and Northern Ireland (the)'), 'London Stock Exchange', '.IL',
        NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'United States of America (the)'),
        'Chicago Board of Trade (CBOT)', '.CBT', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'United States of America (the)'),
        'Chicago Mercantile Exchange (CME)', '.CME', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'United States of America (the)'), 'Dow Jones Indexes',
        NULL, NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'United States of America (the)'), 'NASDAQ Stock Exchange',
        NULL, NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'United States of America (the)'),
        'ICE Futures US, former New York Board of Trade', '.NYB', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'United States of America (the)'),
        'New York Commodities Exchange (COMEX)', '.CMX', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'United States of America (the)'),
        'New York Mercantile Exchange (NYMEX)', '.NYM', NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'United States of America (the)'),
        'Options Price Reporting Authority (OPRA)', NULL, NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'United States of America (the)'),
        'OTC Bulletin Board Market', NULL, NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'United States of America (the)'), 'OTC Markets Group',
        NULL, NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'United States of America (the)'), 'S & P Indices', NULL,
        NOW(), NOW()),
       (gen_random_uuid(), (SELECT id FROM countries WHERE name = 'Venezuela (Bolivarian Republic of)'), 'Caracas Stock Exchange', '.CR', NOW(),
        NOW());

ALTER TABLE assets
    DROP CONSTRAINT assets_ticker_key;

ALTER TABLE assets
    ADD CONSTRAINT asset_ticker_exchange_uq UNIQUE (ticker, stock_exchange_id);