name: checkstyle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Run checkstyle
        uses: dbelyaev/action-checkstyle@v3.10.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          level: error
          fail_level: any
          filter_mode: nofilter

  actions-lint:
    name: runner / github-actions-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Run github actions lint
        uses: reviewdog/action-actionlint@v1.72.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          fail_level: any
          filter_mode: nofilter

  dotenv-lint:
    name: runner / dotenv-linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Run dotenv lint
        uses: dotenv-linter/action-dotenv-linter@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          filter_mode: nofilter

  dockerfile-lint:
    name: runner / hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Run dockerfile lint
        uses: reviewdog/action-hadolint@v1.50.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          filter_mode: nofilter

  yaml-lint:
    name: runner / yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Run yaml lint
        uses: reviewdog/action-yamllint@v1.21.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          filter_mode: nofilter
          fail_level: any
          yamllint_flags: '-d "{extends: default}" .'

  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Run misspell check
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          filter_mode: nofilter
          locale: "US"